version: '{build}'
skip_tags: true
image: Visual Studio 2019
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Serilog.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
