version: '{build}'
skip_tags: true
image: Visual Studio 2019
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Serilog.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 4zf4JU97IDAvIkLf+qegS8/kThDMbAk6vhcX1HVaYihVJ2RKcQez83pJ+9BX/o1s
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
